version: '3.3'

services:
  app: &app
    build: .
    env_file: .env
    links:
      - redis
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000"

  migrate:
    <<: *app
    command: >
      bash -c "python manage.py migrate"
    ports: []
    depends_on:
      - app

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chat
    tmpfs:
      - /var/lib/postgresql/data
    ports:
     - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis

  channels:
    build: .
    command: daphne -b 0.0.0.0 -p 8001 config.asgi:application
    env_file: .env
    depends_on:
      - redis
      - db
    links:
      - redis
    ports:
      - "8001:8001"

